- hosts: debian
  vars:
    - user_name: root
    - app_folder_name: app
    - dockerfile_path: "{{user_name}}/{{app_folder_name}}"
    - docker_image_name: "flask-app-ansible:latest"
    - docker_container_name: "flask-app-ansible"
    - patting_http_port: "80"
  become: true
  tasks:
    - name: Copy app folder to VM machine
      copy:
        src: ./{{app_folder_name}}
        dest: /{{user_name}}

    - name: "Build Docker image from Dockerfile"
      docker_image:
        name:  "{{docker_image_name}}"
        build:
          pull: yes
          path: "{{dockerfile_path}}"
        state: present
        source: build

    - name: "Launch Docker container from image built"
      docker_container:
        name: "{{docker_container_name}}"
        image: "{{docker_image_name}}"
        state: started
        ports:
        - "80:{{patting_http_port}}"
      register: docker_info